# Generated by Django 6.0.6 on 2026-07-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagementsys', '0002_alter_supply_options_rename_price_product_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsRecieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('recieved_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invmanagementsys.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsRecievedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_recieved', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_recieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invmanagementsys.goodsrecieved')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invmanagementsys.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
