# Generated by Django 6.0.6 on 2026-07-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagementsys', '0003_goodsrecieved_goodsrecieveditem_delete_supply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsRecieved',
            new_name='GoodsReceived',
        ),
        migrations.RenameModel(
            old_name='GoodsRecievedItem',
            new_name='GoodsReceivedItem',
        ),
        migrations.RenameField(
            model_name='goodsreceived',
            old_name='recieved_date',
            new_name='received_date',
        ),
        migrations.RenameField(
            model_name='goodsreceiveditem',
            old_name='goods_recieved',
            new_name='goods_received',
        ),
        migrations.RenameField(
            model_name='goodsreceiveditem',
            old_name='quantity_recieved',
            new_name='quantity_received',
        ),
    ]
