# Generated by Django 6.0.6 on 2026-07-18 13:37

import invmanagementsys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagementsys', '0005_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default=invmanagementsys.models.generate_po_number, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Partially Received', 'Partially Received'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
