# Generated by Django 6.0.6 on 2026-07-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagementsys', '0006_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceived',
            options={'verbose_name_plural': 'Goods Received'},
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('received', 'Fully Received'), ('partially', 'Partially Received'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
